version: '0.1'

services:
  # web:
  #   image: node:18
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   command: sh -c "npm install && npm run dev"
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/nextjsdb
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: